[package]
name = "mongodb_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.37.0"
serde = "1.0.198"
chrono = "0.4.38"
mongodb = "2.8.2"
